Repository TriliumNext/Notes, pull requests merged in 2025-06, with the labels that each got.

#2127 fix(llm): don't filter for specific words when pulling models for openai
  apps/server/src/routes/api/openai.ts
Labels: llm

#2092 feat(metrics): add documentation for using grafana dashboard
  README.md
  apps/server/src/assets/doc_notes/en/User Guide/!!!meta.json
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Advanced Usage/1_Metrics_image.png
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Advanced Usage/2_Metrics_image.png
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Advanced Usage/Metrics.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Advanced Usage/Metrics/grafana-dashboard.json
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Advanced Usage/Metrics_image.png
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/Keyboard Shortcuts.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Note Types/Geo Map.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Note Types/Text/Keyboard shortcuts.html
  docs/User Guide/!!!meta.json
  docs/User Guide/User Guide/Advanced Usage/1_Metrics_image.png
  docs/User Guide/User Guide/Advanced Usage/2_Metrics_image.png
  docs/User Guide/User Guide/Advanced Usage/Metrics.md
  docs/User Guide/User Guide/Advanced Usage/Metrics/grafana-dashboard.json
  docs/User Guide/User Guide/Advanced Usage/Metrics_image.png
  docs/User Guide/User Guide/Note Types/Text/Keyboard shortcuts.md
Labels: size:XXL

#2106 fix(llm): Fix Note Embeddings not being synced correctly and causing sync loops
  apps/client/src/services/froca_updater.ts
  apps/client/src/services/load_results.ts
  apps/server/src/becca/becca-interface.ts
  apps/server/src/becca/becca_loader.ts
  apps/server/src/becca/entities/bnote_embedding.ts
  apps/server/src/services/consistency_checks.ts
  apps/server/src/services/ws.ts
Labels: llm

#2123 feat(i18n): description for all keyboard shortcuts
  apps/server/src/assets/translations/en/server.json
  apps/server/src/services/keyboard_actions.ts
Labels: size:M

#2110 LLM Integration, part 3
  apps/client/src/widgets/llm_chat/communication.ts
  apps/client/src/widgets/llm_chat/llm_chat_panel.ts
  apps/client/src/widgets/llm_chat/types.ts
  apps/client/src/widgets/type_widgets/ai_chat.ts
  apps/server/src/routes/api/llm.ts
  apps/server/src/services/llm/ai_service_manager.ts
  apps/server/src/services/llm/chat/handlers/tool_handler.ts
  apps/server/src/services/llm/chat/index.ts
  apps/server/src/services/llm/chat/rest_chat_service.ts
  apps/server/src/services/llm/chat/sessions_store.ts
  apps/server/src/services/llm/config/configuration_helpers.ts
  apps/server/src/services/llm/config/configuration_manager.ts
  apps/server/src/services/llm/context_extractors/index.ts
  apps/server/src/services/llm/embeddings/storage.ts
  apps/server/src/services/llm/interfaces/configuration_interfaces.ts
  apps/server/src/services/llm/pipeline/stages/message_preparation_stage.ts
  apps/server/src/services/llm/pipeline/stages/model_selection_stage.ts
  apps/server/src/services/llm/pipeline/stages/tool_calling_stage.ts
  apps/server/src/services/llm/providers/providers.ts
  apps/server/src/services/llm/tools/search_notes_tool.ts
  apps/server/src/services/llm/tools/tool_registry.ts
Labels: llm

#2136 Calendar template docs update
  apps/edit-docs/demo/!!!meta.json
  apps/edit-docs/demo/index.html
  apps/edit-docs/demo/navigation.html
  apps/edit-docs/demo/root/Journal.dat
  apps/edit-docs/demo/root/Trilium Demo.html
  apps/edit-docs/demo/root/Trilium Demo/Books/Book template.html
  apps/edit-docs/demo/root/Trilium Demo/Books/To read.html
  apps/edit-docs/demo/root/Trilium Demo/Formatting examples/Checkbox lists.html
  apps/edit-docs/demo/root/Trilium Demo/Formatting examples/Code blocks.html
  apps/edit-docs/demo/root/Trilium Demo/Formatting examples/Math.html
  apps/edit-docs/demo/root/Trilium Demo/Inbox/The Last Question.html
  apps/edit-docs/demo/root/Trilium Demo/Journal.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/11 - November/28 - Tuesday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/11 - November/28 - Tuesday/Christmas gift ideas.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/11 - November/28 - Tuesday/Trusted timestamping.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/18 - Monday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/19 - Tuesday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/20 - Wednesday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/21 - Thursday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/22 - Friday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/23 - Saturday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/24 - Sunday - Christmas Eve!.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/24 - Sunday - Christmas Eve!/DONE - Buy a board game for Al.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/30 - Thursday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/Day template.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/Chichén Itzá, Mexico.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/Christ the Redeemer, Brazil.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/Machu Picchu, Peru.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/Petra, Jordan.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/The Colosseum, Rome, Italy.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/The Great Wall of China.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/The Taj Mahal, India.html
  apps/edit-docs/demo/root/Trilium Demo/Scripting examples/Task manager.html
  apps/edit-docs/demo/root/Trilium Demo/Scripting examples/Task manager/Done/Buy a board game for Alice.html
  apps/edit-docs/demo/root/Trilium Demo/Scripting examples/Task manager/Locations/mall/Buy some book for Bob/Maybe Black Swan.html
  apps/edit-docs/demo/root/Trilium Demo/Tech/Linux/Bash scripting.html
  apps/edit-docs/demo/root/Trilium Demo/Tech/Linux/Bash scripting/Bash startup modes.html
  apps/edit-docs/demo/root/Trilium Demo/Tech/Linux/Bash scripting/While loop.html
  apps/edit-docs/demo/root/Trilium Demo/Tech/Node.js/Overview/Platform architecture.html
  apps/server/src/assets/db/demo.zip
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Advanced Usage/Advanced Showcases/Day Notes.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Advanced Usage/Templates.html
  apps/server/src/services/date_notes.ts
  apps/server/src/services/notes.ts
  docs/User Guide/!!!meta.json
  docs/User Guide/User Guide/Advanced Usage/Advanced Showcases/Day Notes.md
  docs/User Guide/User Guide/Advanced Usage/Templates.md
Labels: size:L

#2179 docs: ✏️ Fix Journal demo relation name
  apps/edit-docs/demo/!!!meta.json
  apps/edit-docs/demo/root/Trilium Demo.html
  apps/edit-docs/demo/root/Trilium Demo/Books/Book template.html
  apps/edit-docs/demo/root/Trilium Demo/Books/To read.html
  apps/edit-docs/demo/root/Trilium Demo/Formatting examples/Checkbox lists.html
  apps/edit-docs/demo/root/Trilium Demo/Formatting examples/Code blocks.html
  apps/edit-docs/demo/root/Trilium Demo/Formatting examples/Math.html
  apps/edit-docs/demo/root/Trilium Demo/Inbox/The Last Question.html
  apps/edit-docs/demo/root/Trilium Demo/Journal.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/11 - November/28 - Tuesday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/11 - November/28 - Tuesday/Christmas gift ideas.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/11 - November/28 - Tuesday/Trusted timestamping.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/18 - Monday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/19 - Tuesday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/20 - Wednesday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/21 - Thursday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/22 - Friday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/23 - Saturday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/24 - Sunday - Christmas Eve!.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/24 - Sunday - Christmas Eve!/DONE - Buy a board game for Al.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/2021/12 - December/30 - Thursday.html
  apps/edit-docs/demo/root/Trilium Demo/Journal/Day template.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/Chichén Itzá, Mexico.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/Christ the Redeemer, Brazil.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/Machu Picchu, Peru.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/Petra, Jordan.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/The Colosseum, Rome, Italy.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/The Great Wall of China.html
  apps/edit-docs/demo/root/Trilium Demo/Note Types/Geo Map (The Seven Wonders of the World)/The Taj Mahal, India.html
  apps/edit-docs/demo/root/Trilium Demo/Scripting examples/Task manager.html
  apps/edit-docs/demo/root/Trilium Demo/Scripting examples/Task manager/Done/Buy a board game for Alice.html
  apps/edit-docs/demo/root/Trilium Demo/Scripting examples/Task manager/Locations/mall/Buy some book for Bob/Maybe Black Swan.html
  apps/edit-docs/demo/root/Trilium Demo/Tech/Linux/Bash scripting.html
  apps/edit-docs/demo/root/Trilium Demo/Tech/Linux/Bash scripting/Bash startup modes.html
  apps/edit-docs/demo/root/Trilium Demo/Tech/Linux/Bash scripting/While loop.html
  apps/edit-docs/demo/root/Trilium Demo/Tech/Node.js/Overview/Platform architecture.html
  apps/server/src/assets/db/demo.zip
Labels: size:M

#2083 feat: Add configurable date/time format for Alt+T shortcut
  apps/client/src/services/keyboard_actions.ts
  apps/client/src/services/utils.ts
  apps/client/src/translations/en/translation.json
  apps/client/src/widgets/type_widgets/ckeditor/config.ts
  apps/client/src/widgets/type_widgets/content_widget.ts
  apps/client/src/widgets/type_widgets/editable_text.ts
  apps/client/src/widgets/type_widgets/options/text_notes/date_time_format.ts
  apps/server/src/routes/api/options.ts
  packages/ckeditor5/src/icons/date-time.svg
  packages/ckeditor5/src/plugins.ts
  packages/ckeditor5/src/plugins/insert_date_time.ts
  packages/commons/src/lib/options_interface.ts
Labels: size:L

#2198 Support custom oidc server
  apps/server/src/assets/config-sample.ini
  apps/server/src/assets/translations/cn/server.json
  apps/server/src/assets/translations/en/server.json
  apps/server/src/assets/views/login.ejs
  apps/server/src/routes/login.ts
  apps/server/src/services/config.ts
  apps/server/src/services/open_id.ts
Labels: size:M

#2217 feat(llm): add warning to the top of LLM Chat Notes and LLM settings that the feature is experimental
  apps/client/src/translations/en/translation.json
  apps/client/src/widgets/llm_chat/validation.ts
  apps/client/src/widgets/type_widgets/options/ai_settings/ai_settings_widget.ts
Labels: size:S

#2206 fix(server): increment SYNC_VERSION and APP_DB_VERSION for LLM embedd…
  apps/server/src/services/app_info.ts
Labels: size:XS

#2218 Doc: Updated theme reference
  docs/User Guide/User Guide/Theme development/Reference.md
Labels: size:XS

#2208 fix(llm): save to the same note that the chat request was sent from
  apps/client/src/widgets/llm_chat/llm_chat_panel.ts
  apps/client/src/widgets/type_widgets/ai_chat.ts
  apps/client/src/widgets/type_widgets/options/ai_settings/ai_settings_widget.ts
  apps/server/src/services/llm/ai_service_manager.ts
  apps/server/src/services/llm/config/configuration_helpers.ts
  apps/server/src/services/llm/config/configuration_manager.ts
  apps/server/src/services/llm/pipeline/stages/model_selection_stage.ts
  apps/server/src/services/llm/providers/providers.ts
  apps/server/src/services/options.ts
Labels: size:XL

#2219 Doc: update Nginx reverse proxy documentation
  docs/User Guide/User Guide/Installation & Setup/Server Installation/2. Reverse proxy/Nginx.md
Labels: size:S

#2209 feat(llm): add unit tests
  apps/server-e2e/src/ai_settings.spec.ts
  apps/server-e2e/src/llm_chat.spec.ts
  apps/server/src/routes/api/llm.spec.ts
  apps/server/src/routes/api/llm.ts
  apps/server/src/routes/route_api.ts
  apps/server/src/services/llm/ai_service_manager.spec.ts
  apps/server/src/services/llm/chat/rest_chat_service.spec.ts
  apps/server/src/services/llm/chat/rest_chat_service.ts
  apps/server/src/services/llm/chat/utils/message_formatter.spec.ts
  apps/server/src/services/llm/chat_service.spec.ts
  apps/server/src/services/llm/chat_storage_service.spec.ts
  apps/server/src/services/llm/chat_storage_service.ts
  apps/server/src/services/llm/config/configuration_helpers.spec.ts
  apps/server/src/services/llm/context/services/context_service.spec.ts
  apps/server/src/services/llm/model_capabilities_service.spec.ts
  apps/server/src/services/llm/pipeline/chat_pipeline.spec.ts
  apps/server/src/services/llm/providers/anthropic_service.spec.ts
  apps/server/src/services/llm/providers/integration/streaming.spec.ts
  apps/server/src/services/llm/providers/ollama_service.spec.ts
  apps/server/src/services/llm/providers/openai_service.spec.ts
  apps/server/src/services/llm/providers/stream_handler.spec.ts
  apps/server/src/services/llm/providers/stream_handler.ts
  apps/server/src/services/llm/streaming/error_handling.spec.ts
  apps/server/src/services/llm/streaming/tool_execution.spec.ts
  apps/server/src/services/llm/tools/tool_registry.spec.ts
  apps/server/src/services/ws.spec.ts
Labels: size:XXL

#2230 Tab row scroll
  apps/client/src/widgets/tab_row.ts
Labels: size:S

#2232 feat(ckeditor): Add text alignment
  apps/client/src/widgets/type_widgets/ckeditor/config.ts
  packages/ckeditor5/src/plugins.ts
Labels: size:XS

#2236 fix(zen): Show fixed toolbar in Zen mode
  apps/client/src/stylesheets/style.css
Labels: size:XS

#2220 fix(move_block): move multiple lines up/down
  packages/ckeditor5/src/plugins/move_block_updown.ts
Labels: size:L

#2285 fix(build): fix Nx project discovery issue caused by parent .gitignore
  .gitignore
Labels: size:XS

#2293 fix(tree): Unexpected collapse after hoisting a note
  apps/client/src/widgets/note_tree.ts
Labels: size:XS

#2281 fix(client): show warning/error when app is using Rosetta 2 translation (running wrong arch)
  apps/client/src/components/app_context.ts
  apps/client/src/components/startup_checks.ts
  apps/client/src/desktop.ts
  apps/client/src/layouts/layout_commons.ts
  apps/client/src/translations/en/translation.json
  apps/client/src/widgets/dialogs/incorrect_cpu_arch.ts
  apps/server/src/routes/api/system_info.ts
  apps/server/src/routes/routes.ts
Labels: size:L

#2303 fix(image): ensure images opened in a new tab can be activated
  apps/client/src/widgets/type_widgets/abstract_text_type_widget.ts
Labels: size:XS

#2331 fix(context menu): not auto-closing on mobile
  apps/client/src/menus/context_menu.ts
  apps/client/src/stylesheets/style.css
Labels: size:S

#2336 Slash commands
  apps/client/.env.development
  apps/client/.env.production
  apps/client/src/services/utils.ts
  apps/client/src/stylesheets/style.css
  apps/client/src/stylesheets/theme-next/notes/text.css
  apps/client/src/vite-env.d.ts
  apps/client/src/widgets/dialogs/add_link.ts
  apps/client/src/widgets/type_widgets/ckeditor/config.ts
  apps/client/src/widgets/type_widgets/editable_text.ts
  packages/ckeditor5-admonition/src/index.ts
  packages/ckeditor5-math/src/index.ts
  packages/ckeditor5/package.json
  packages/ckeditor5/src/extra_slash_commands.ts
  packages/ckeditor5/src/index.ts
  packages/ckeditor5/src/plugins.ts
  packages/ckeditor5/src/plugins/includenote.ts
  packages/ckeditor5/src/plugins/insert_date_time.ts
  packages/ckeditor5/src/plugins/internallink.ts
  packages/ckeditor5/src/plugins/markdownimport.ts
  pnpm-lock.yaml
Labels: size:L

#2344 Text snippets
  apps/client/src/components/app_context.ts
  apps/client/src/services/froca.ts
  apps/client/src/services/note_types.ts
  apps/client/src/stylesheets/style.css
  apps/client/src/types-assets.d.ts
  apps/client/src/widgets/type_widgets/ckeditor/config.ts
  apps/client/src/widgets/type_widgets/ckeditor/snippets.ts
  apps/client/src/widgets/type_widgets/editable_text.ts
  apps/server/src/services/hidden_subtree.ts
  apps/server/src/services/hidden_subtree_templates.ts
  packages/ckeditor5/src/index.ts
  packages/ckeditor5/src/plugins.ts
  packages/commons/src/lib/hidden_subtree.ts
Labels: size:L

#2329 flake: fix Electron version, fix Wayland support, fix source filter
  apps/server/src/services/window.ts
  flake.nix
Labels: desktop-app, size:S

#2357 fix(website): update README.md instructions
  apps/website/README.md
Labels: documentation, size:M

#2356 fix(client): link to API documentation
  apps/client/src/widgets/floating_buttons/code_buttons.ts
Labels: size:XS

#2342 feat(autocomplete): support specifying path when creating a new note
  apps/client/src/services/note_autocomplete.ts
  apps/client/src/services/note_create.ts
  apps/client/src/translations/en/translation.json
  apps/client/src/widgets/dialogs/note_type_chooser.ts
Labels: size:M

#2345 feat(server): lint for trailing slashes in sync URL and extra slashes…
  apps/server/src/routes/custom.ts
  apps/server/src/services/sync_options.ts
  apps/server/src/services/utils.spec.ts
  apps/server/src/services/utils.ts
Labels: size:L

#2371 chore(i18n): update Spanish translation
  _regroup/bin/translation.sh
  apps/client/src/translations/es/translation.json
  apps/server/src/assets/translations/es/server.json
Labels: size:L
